# Generated by Django 4.1.3 on 2022-12-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_alter_myuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
