# Generated by Django 4.1.3 on 2022-12-10 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_alter_myuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
