# Generated by Django 4.1.3 on 2022-12-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0008_mytask_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytask',
            old_name='user_id',
            new_name='Foreign_id',
        ),
    ]
