# Generated by Django 4.1.3 on 2022-12-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_alter_myuser_token_mytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
